version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./easyDoser-frontend/Dockerfile
    command: npm start
    volumes:
    - ./easyDoser-frontend/src:/frontend/src
    - ./easyDoser-frontend/public:/frontend/public
    ports:
      - "3000:3000"
    stdin_open: true
