version: "3"
services:
  api:
    image: abhimanyu121/easydoser:server-latest
    build:
      context: .
      dockerfile: ./easyDoser-server/Dockerfile
    volumes:
      - /run/media/abhimanyu/265C6B275C6AF14B/fabric/test-network/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp:/mspconfig
      - /run/media/abhimanyu/265C6B275C6AF14B/fabric/config:/config
      - ./easyDoser-server/:/server/
    environment :
      - CORE_PEER_MSPCONFIGPATH=/mspconfig
      - FABRIC_CFG_PATH=/config
      - FABRIC=/server/bin
    ports:
      - "8080:8080"
    network_mode: "host"
    stdin_open: true
  web:
    image: abhimanyu121/easydoser:web-latest
    build:
      context: .
      dockerfile: ./easyDoser-frontend/Dockerfile
    volumes:
    - ./easyDoser-frontend/src:/frontend/src
    - ./easyDoser-frontend/public:/frontend/public  
    ports:
      - "5000:5000"
    depends_on:
      - api
    network_mode: "host"  
    stdin_open: true

# Your paths will look somewhat like this
  # - /run/media/abhimanyu/265C6B275C6AF14B/fabric/config:/config
  # - /run/media/abhimanyu/265C6B275C6AF14B/fabric/test-network/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp:/mspconfig
 
 
  # - /run/media/abhimanyu/265C6B275C6AF14B/fabric/bin:/server/bin