apiVersion: v1
kind: Pod
metadata:
  name: easydoser
  labels:
    app: server
spec:
  hostNetwork: true
  containers:
    - name: server
      image: abhimanyu121/easydoser:server-latest
    - name: web
      image: abhimanyu121/easydoser:web-latest
      ports:
        - containerPort: 8080
        - containerPort: 5000
      volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /mspconfig
          name: mspconfig
  volumes:
    - name: mspconfig
      hostPath:
        path: /run/media/abhimanyu/265C6B275C6AF14B/fabric/test-network/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
    - name: config
      hostPath:
        path: /run/media/abhimanyu/265C6B275C6AF14B/fabric/config
